const translations={
  id:{
    'nav.work':'Karya','nav.about':'Tentang','nav.experience':'Pengalaman','nav.contact':'Kontak',
    'hero.status':'Terbuka untuk peluang data & AI','hero.line1':'Saya mengubah data kompleks','hero.line2':'menjadi produk yang berguna.','hero.intro':'Data Scientist dan Machine Learning Engineer yang berfokus pada AI praktis, analisis yang jelas, dan produk yang benar-benar bisa digunakan.','hero.cta':'Lihat karya pilihan','hero.email':'Kirim email ↗','hero.role':'Data · ML · AI',
    'work.kicker':'Karya pilihan','work.title':'Beberapa karya yang paling saya banggakan.','work.lede':'Pilihan yang fokus—cukup konteks untuk memahami masalah, peran saya, dan hasilnya.','work.motion':'Arahkan untuk preview','work.more':'Proyek lainnya',
    'project.nextgen':'Sistem rekomendasi berbasis AI dan big data untuk pengembangan kompetensi ASN, dibangun saat magang di Kementerian Pekerjaan Umum.','project.nextgenRole':'Machine Learning Specialist','project.chattax':'Asisten pajak yang menggabungkan Mistral 7B hasil fine-tuning dengan RAG untuk menjawab berdasarkan dokumen regulasi terbaru.','project.anevia':'Aplikasi web deteksi dini anemia menggunakan segmentasi citra mata, dirancang agar skrining lebih mudah diakses.',
    'labels.role':'Peran','labels.present':'Sekarang','about.kicker':'Profil','about.title':'Kedalaman teknis, disampaikan dengan jelas.','about.lead':'Saya mahasiswa Ilmu Komputer Universitas Gunadarma dengan IPK 3,99. Saya menikmati proses lengkap dari data yang berantakan dan eksperimen hingga cerita yang jelas dan produk yang berfungsi.','about.detail':'Pekerjaan saya mencakup machine learning, NLP, computer vision, sistem rekomendasi, dan visualisasi data. Saya paling nyaman saat mengubah analisis menjadi sesuatu yang dapat dipahami dan ditindaklanjuti tim.',
    'experience.kicker':'Pengalaman','experience.title':'Belajar dengan membangun, mempresentasikan, dan menyelesaikan.','experience.puTitle':'Magang Machine Learning Specialist','experience.puText':'Membangun NextGen, sistem rekomendasi kompetensi berbasis AI dan big data yang terotomasi serta terintegrasi dengan Google Cloud Platform.','experience.pitchTitle':'Best AI Integration Award','experience.pitchText':'Mewakili Indonesia dengan MeatSure bersama tim dari Rusia dan Uzbekistan.','experience.campTitle':'Lulusan Coding Camp','experience.campText':'Menyelesaikan program intensif enam bulan dengan nilai akhir 97,0.','experience.eduTitle':'Ilmu Komputer',
    'capabilities.kicker':'Kemampuan','capabilities.title':'Hal yang saya bawa ke dalam tim.','capabilities.ml':'Machine Learning','capabilities.data':'Data & Insight','capabilities.ai':'AI Terapan','capabilities.product':'Product Thinking','capabilities.productText':'Komunikasi jelas, kolaborasi, dan penyelesaian yang praktis',
    'resume.kicker':'Resume','resume.title':'Versi satu menit.','resume.label':'WIEFRAN VARENZO — PROFIL','resume.role':'Data Scientist & Machine Learning Engineer','resume.summary':'Mahasiswa Ilmu Komputer dengan IPK 3,99, pengalaman langsung membangun produk AI, serta rekam jejak di machine learning, analisis data, dan presentasi teknis.','resume.cta':'Minta PDF terbaru ↗','credentials.kicker':'Kredensial & media','credentials.title':'Bukti di luar kartu proyek.','media.pu':'Magang Kementerian Pekerjaan Umum','media.pitch':'Best AI Integration Award','media.camp':'Lulusan Coding Camp','contact.kicker':'Kontak','contact.title':'Punya masalah data yang layak diselesaikan?','contact.cta':'Mari bicara','footer.top':'Kembali ke atas ↑'
  }
};
const root=document.documentElement;
const langButton=document.querySelector('#language-toggle');
const themeButton=document.querySelector('#theme-toggle');
let lang=localStorage.getItem('lang')||'en';
function applyLanguage(){root.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(lang==='id'&&translations.id[key]){if(!el.dataset.en)el.dataset.en=el.textContent;el.textContent=translations.id[key]}else if(el.dataset.en){el.textContent=el.dataset.en}});langButton.textContent=lang==='en'?'ID':'EN';langButton.setAttribute('aria-label',lang==='en'?'Switch to Bahasa Indonesia':'Switch to English')}
langButton.addEventListener('click',()=>{lang=lang==='en'?'id':'en';localStorage.setItem('lang',lang);applyLanguage()});applyLanguage();
themeButton.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('theme',next);document.querySelector('meta[name="theme-color"]').content=next==='dark'?'#111210':'#f2f0e9'});
const menuButton=document.querySelector('#menu-toggle');const mobileNav=document.querySelector('#mobile-nav');menuButton.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});
const syncRevealVisibility=()=>{const viewport=window.innerHeight||document.documentElement.clientHeight;document.querySelectorAll('.reveal').forEach(el=>{const rect=el.getBoundingClientRect();if(el.matches('.project, .project-card, .project-featured, .project-showcase-card')){el.classList.add('visible');el.classList.remove('reveal');return;}if(rect.top<viewport*.98&&rect.bottom>0){el.classList.add('visible');if(observer){observer.unobserve(el);}}});};
const observeRevealTargets=()=>{document.querySelectorAll('.reveal').forEach(el=>{if(el.matches('.project, .project-card, .project-featured, .project-showcase-card')){el.classList.add('visible');el.classList.remove('reveal');return;}if(!el.dataset.revealObserved){observer.observe(el);el.dataset.revealObserved='true'}});syncRevealVisibility()};
observeRevealTargets();
const revealMutationObserver=new MutationObserver(()=>observeRevealTargets());
revealMutationObserver.observe(document.body,{childList:true,subtree:true});
window.addEventListener('scroll',syncRevealVisibility,{passive:true});
window.addEventListener('resize',syncRevealVisibility);
document.querySelectorAll('.motion-media').forEach(media=>{const syncHoverState=state=>{media.classList.toggle('is-hovered',state); media.querySelectorAll('.nav-zone').forEach(zone=>{zone.style.opacity=state?'1':'0'; zone.style.pointerEvents=state?'auto':'none';});};media.addEventListener('mouseenter',()=>syncHoverState(true));media.addEventListener('mouseleave',()=>syncHoverState(false));media.addEventListener('focusin',()=>syncHoverState(true));media.addEventListener('focusout',()=>syncHoverState(false));
  const sources=(media.dataset.sources||'').split(',').map(item=>item.trim()).filter(Boolean); if(sources.length<2)return;
  let index=0; const [frameA, frameB]=media.querySelectorAll('.motion-frame');
  const applySlide=newIndex=>{const current=sources[newIndex]; const next=sources[(newIndex+1)%sources.length]; frameA.src=current; frameB.src=next; frameA.alt=media.getAttribute('aria-label')||frameA.alt; frameB.alt=frameA.alt; media.dataset.index=String(newIndex);};
  const moveSlide=direction=>{index=(index+direction+sources.length)%sources.length; media.classList.add('is-flipping'); requestAnimationFrame(()=>{applySlide(index); frameA.style.opacity='0.25'; frameB.style.opacity='1'; frameA.style.transform='scale(1.04) translateX(-4%)'; frameB.style.transform='scale(1) translateX(0)'; setTimeout(()=>{frameA.style.opacity=''; frameA.style.transform=''; frameB.style.opacity=''; frameB.style.transform=''; media.classList.remove('is-flipping');},280)});};
  media.querySelector('.nav-zone-prev')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();moveSlide(-1)});
  media.querySelector('.nav-zone-next')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();moveSlide(1)});
  media.querySelector('.nav-zone-prev')?.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();moveSlide(-1)}});
  media.querySelector('.nav-zone-next')?.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();moveSlide(1)}});
  applySlide(index);});
document.querySelector('#year').textContent=new Date().getFullYear();
